apiVersion: v1
kind: Pod
metadata:
  name: catalog-cart
  namespace: default
  labels:
    name: catalog-cart
spec:
  containers:
    - image: lee71559/catalog-cart:v1
      name: catalog-cart
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP