
version: "3"

services:
  db-management :
    image: db-management 
    volumes:
      - /tmp:/tmp
    networks:
      - network   
    ports:
      - 8080 
    environment:
      MYSQL_HOST: "mysql"   
    restart: always     
  lb:
    image: eeacms/haproxy
    depends_on:
    - db-management 
    ports:
    - "80:5000"
    - "1936:1936"
    environment:
      BACKENDS: "db-management "
      BACKENDS_PORT: "8080"
      DNS_ENABLED: "true"
      COOKIES_ENABLED: "true"
      LOG_LEVEL: "info"
    networks:
      - network

volumes:
  schemas:
    external: false

networks:
  network:
    name: grocerydb
    driver: bridge
