apiVersion: v1
kind: Pod
metadata:
  name: spring-payments
  namespace: default
  labels:
    name: spring-payments
spec:
  containers:
    - image: v0zz/spring-payments:v1
      name: spring-payments
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP